const firstPageData = {
  page: {
    cover: '',
    name: 'Note ',
    createdTime: '1630687828342',
    id: 'uba9uqkk2hhfh4m',
    tags: [
      {
        color: '#BFEBFE',
        name: 'note',
      },
    ],
    parentId: '',
    blocks: [
      'dk75vhqipqis558',
      '9w1lg6e7w8v6wsz',
      '3iqx0vh6ap3794r',
      'fhj7t6ckg5j1n1g',
      'jmsrbxrhhmxnyw',
      '4109or7kftym0w7',
      'u4sljmzfw0o69jq',
      '5huu2lqe4quhvbb',
      'bg415c0t7autn0k',
      '3prrrwphj7otqml',
      'yfr1xh4mtfquemc',
      '5nqu6bv43mruiph',
      'km1vjfl7r4upp9',
      '752nh83f12euubg',
      '7wsp7qnhifwvgxh',
      'rqqp7hlyfreyfuj',
      'pa5km4g2zjzbzm',
      'uhvuoju70er0waj',
      'l03j48338zn1j1n',
      'kqj8ek8jph82137',
      'ywssaqsldz2g8b',
      '83w8xq8b822kei',
      'bf3fq1juqd96fka',
      '6bvv9bf4vf56gyh',
      '0xd21yzjcr7zi4r',
      '94s76m9vrpi0mxv',
      'rolwh0wa2k0o83',
      'zxcjhb8i2k4e6i',
      'qv1alsaphsc4lne',
      'un7cpjleudaeu8',
      'yql3atld6wiwu5',
      'ameiyp6qntwi4p3',
      'qd8fvpxnrveblfn',
      'bxohjj3gt2c619x',
      'gronzht7jrja1fd',
      'wjmgset6w6h5f4',
      'sralaqrt1zeii3y',
      'apcudm5mskuk93s',
      'iu8m7k4ca2ao75b',
      'lvrl4irw23oiri',
      'vt5ca2owpqbepe',
      'a0g37lp49iebohl',
      'pie9npuhsccna9',
      'xirwbktp98rw9p',
      '7vi9tcnt0ovs3hx',
      '8b4l84jxl6jv4jv',
      'ff77g71bybvpur',
      'q58gjuch6fdw8er',
      'gnqa4830deu4bwq',
      '4jyvq3zqohr65d5',
      'pqwq48p6d69hl',
      'pi756lq8l69pt',
      'gjuzhaevak69uy',
      'gpzw3je85x46a02',
      'sfb0jwfxhtc6a4y',
      '4p6s13i710c6aa2',
      '5qv6c1s026c6afe',
      'hvycs1fo0nf6aky',
      'zkpv72dinwc6aqa',
      'xiuck8vc7tc6avu',
      'rax7q8qawqf6b1e',
      'upba9dfscmi6b6q',
      'dwyxkti2af6bde',
    ],
    editTime: '1630934644625',
  },
  blocks: [
    {
      type: 'h2',
      id: 'dk75vhqipqis558',
      parentId: '',
      content: {
        html: '專案介紹',
        text: '專案介紹',
      },
      className: 'style-text-color__default',
    },
    {
      type: 'quote',
      id: '9w1lg6e7w8v6wsz',
      parentId: '',
      content: {
        text: 'Note是一個筆記軟體',
        html: 'Note是一個筆記軟體',
      },
      className: 'style-text-color__default',
    },
    {
      type: 'p',
      id: '3iqx0vh6ap3794r',
      parentId: '',
      content: {
        text: '主要功能參考至筆記軟體notion，目前為Beta測試版，後續會增加更多實用功能',
        html: '主要功能參考至筆記軟體notion，目前為Beta測試版，後續會增加更多實用功能',
      },
      className: 'style-text-color__default',
    },
    {
      type: 'p',
      id: 'fhj7t6ckg5j1n1g',
      parentId: '',
      content: {
        text: '',
        html: '',
      },
      className: 'style-text-color__default',
    },
    {
      type: 'p',
      id: 'jmsrbxrhhmxnyw',
      parentId: '',
      content: {
        text: '主要開發都是在web上，因此最好使用電腦來操作此網頁，若是使用手機來操作，可能尚有許多問題',
        html: '主要開發都是在web上，因此最好使用電腦來操作此網頁，若是使用手機來操作，可能尚有許多問題',
      },
      className: 'style-text-color__default',
    },
    {
      type: 'p',
      id: '4109or7kftym0w7',
      parentId: '',
      content: {
        text: '',
        html: '',
      },
      className: 'style-text-color__default',
    },
    {
      type: 'h2',
      id: 'u4sljmzfw0o69jq',
      parentId: '',
      content: {
        html: '涉及知識點',
        text: '涉及知識點',
      },
      className: 'style-text-color__default',
    },
    {
      type: 'dividingLine',
      id: '5huu2lqe4quhvbb',
      parentId: '',
      content: '',
      className: 'style-text-color__default',
    },
    {
      type: 'bulletItem',
      id: 'bg415c0t7autn0k',
      parentId: '',
      content: {
        text: 'vue 3',
        html: 'vue 3',
        indent: 0,
      },
      className: 'style-text-color__default',
    },
    {
      type: 'bulletItem',
      id: '3prrrwphj7otqml',
      parentId: '',
      content: {
        text: 'composition api',
        html: 'composition api',
        indent: 1,
      },
      className: 'style-text-color__red',
    },
    {
      type: 'bulletItem',
      id: 'yfr1xh4mtfquemc',
      parentId: '',
      content: {
        text: '遞迴組件(樹狀結構)',
        html: '遞迴組件(樹狀結構)',
        indent: 1,
      },
      className: 'style-text-color__default',
    },
    {
      type: 'bulletItem',
      id: '5nqu6bv43mruiph',
      parentId: '',
      content: {
        text: 'vuex 4',
        html: 'vuex 4',
        indent: 0,
      },
      className: 'style-text-color__default',
    },
    {
      type: 'bulletItem',
      id: 'km1vjfl7r4upp9',
      parentId: '',
      content: {
        text: '使用modules管理不同的數據',
        html: '使用modules管理不同的數據',
        indent: 1,
      },
      className: 'style-text-color__default',
    },
    {
      type: 'bulletItem',
      id: '752nh83f12euubg',
      parentId: '',
      content: {
        text: 'store.watch監聽state變化順便更新到資料庫',
        html: 'store.watch監聽state變化順便更新到資料庫',
        indent: 1,
      },
      className: 'style-text-color__default',
    },
    {
      type: 'bulletItem',
      id: '7wsp7qnhifwvgxh',
      parentId: '',
      content: {
        text: 'store.subscribe監聽mutation的更新',
        html: 'store.subscribe監聽mutation的更新',
        indent: 1,
      },
      className: 'style-text-color__default',
    },
    {
      type: 'bulletItem',
      id: 'rqqp7hlyfreyfuj',
      parentId: '',
      content: {
        text: 'vue router 4',
        html: 'vue router 4',
        indent: 0,
      },
      className: 'style-text-color__default',
    },
    {
      type: 'bulletItem',
      id: 'pa5km4g2zjzbzm',
      parentId: '',
      content: {
        text: '路由導航',
        html: '路由導航',
        indent: 1,
      },
      className: 'style-text-color__default',
    },
    {
      type: 'bulletItem',
      id: 'uhvuoju70er0waj',
      parentId: '',
      content: {
        text: '套件',
        html: '套件',
        indent: 0,
      },
      className: 'style-text-color__default',
    },
    {
      type: 'bulletItem',
      id: 'l03j48338zn1j1n',
      parentId: '',
      content: {
        text: 'secure LS (localstorage加密)',
        html: 'secure LS (localstorage加密)',
        indent: 1,
      },
      className: 'style-text-color__default',
    },
    {
      type: 'bulletItem',
      id: 'kqj8ek8jph82137',
      parentId: '',
      content: {
        text: 'prismjs (程式碼高亮顯示)',
        html: 'prismjs (程式碼高亮顯示)',
        indent: 1,
      },
      className: 'style-text-color__default',
    },
    {
      type: 'bulletItem',
      id: 'ywssaqsldz2g8b',
      parentId: '',
      content: {
        text: 'bootstrap 5.0',
        html: 'bootstrap 5.0',
        indent: 1,
      },
      className: 'style-text-color__default',
    },
    {
      type: 'bulletItem',
      id: '83w8xq8b822kei',
      parentId: '',
      content: {
        text: 'font awesome 5.0',
        html: 'font awesome 5.0',
        indent: 1,
      },
      className: 'style-text-color__default',
    },
    {
      type: 'bulletItem',
      id: 'bf3fq1juqd96fka',
      parentId: '',
      content: {
        text: 'scss',
        html: 'scss',
        indent: 1,
      },
      className: 'style-text-color__default',
    },
    {
      type: 'bulletItem',
      id: '6bvv9bf4vf56gyh',
      parentId: '',
      content: {
        text: 'eslint (使用airbnb風格)',
        html: 'eslint (使用airbnb風格)',
        indent: 1,
      },
      className: 'style-text-color__default',
    },
    {
      type: 'bulletItem',
      id: '0xd21yzjcr7zi4r',
      parentId: '',
      content: {
        text: 'firebase',
        html: 'firebase',
        indent: 1,
      },
      className: 'style-text-color__default',
    },
    {
      type: 'bulletItem',
      id: '94s76m9vrpi0mxv',
      parentId: '',
      content: {
        text: 'Authentication',
        html: 'Authentication',
        indent: 2,
      },
      className: 'style-text-color__default',
    },
    {
      type: 'bulletItem',
      id: 'rolwh0wa2k0o83',
      parentId: '',
      content: {
        text: 'firestore',
        html: 'firestore',
        indent: 2,
      },
      className: 'style-text-color__default',
    },
    {
      type: 'bulletItem',
      id: 'zxcjhb8i2k4e6i',
      parentId: '',
      content: {
        text: '使用到的api',
        html: '使用到的api',
        indent: 0,
      },
      className: 'style-text-color__default',
    },
    {
      type: 'bulletItem',
      id: 'qv1alsaphsc4lne',
      parentId: '',
      content: {
        text: 'LinkPreview API',
        html: 'LinkPreview API',
        indent: 1,
      },
      className: 'style-text-color__default',
    },
    {
      type: 'p',
      id: 'un7cpjleudaeu8',
      parentId: '',
      content: {
        text: '',
        html: '',
      },
      className: 'style-text-color__default',
    },
    {
      type: 'h2',
      id: 'yql3atld6wiwu5',
      parentId: '',
      content: {
        html: '功能說明',
        text: '功能說明',
      },
      className: 'style-text-color__default',
    },
    {
      type: 'dividingLine',
      id: 'ameiyp6qntwi4p3',
      parentId: '',
      content: '',
      className: 'style-text-color__default',
    },
    {
      type: 'p',
      id: 'qd8fvpxnrveblfn',
      parentId: '',
      content: {
        text: '完整功能可以參考以下連結(或者如果是Notion使用者，可以依照對Notion的經驗自己嘗試玩看看~)',
        html: '完整功能可以參考以下連結(或者如果是Notion使用者，可以依照對Notion的經驗自己嘗試玩看看~)',
      },
      className: 'style-text-color__default',
    },
    {
      type: 'linkPreview',
      id: 'bxohjj3gt2c619x',
      parentId: '',
      content: {
        title: 'Note - HackMD',
        description: '![](https://i.imgur.com/p924bGV.png) # Note > Note是一個筆記軟體 主要功能參考至notion。目前為測試版，有許多小問題... 後續會增',
        image: 'https://www.gravatar.com/avatar/dbcf568e433f289f7e93f61f9dedbb7e?s=400',
        url: 'https://hackmd.io/@Wins/SyqEdjwfD',
      },
      className: 'style-text-color__default',
    },
    {
      type: 'p',
      id: 'gronzht7jrja1fd',
      parentId: '',
      content: {
        text: '',
        html: '',
      },
      className: 'style-text-color__default',
    },
    {
      type: 'h2',
      id: 'wjmgset6w6h5f4',
      parentId: '',
      content: {
        text: '關於資料的更新和保存',
        html: '關於資料的更新和保存',
      },
      className: 'style-text-color__purple',
    },
    {
      type: 'dividingLine',
      id: 'sralaqrt1zeii3y',
      parentId: '',
      content: '',
      className: 'style-text-color__default',
    },
    {
      type: 'p',
      id: 'apcudm5mskuk93s',
      parentId: '',
      content: {
        text: '原本最初的作法是 : 修改數據就更新到firestore數據庫上，結果某一次測試輸入太多文字，firestore就爆流量限制問題了...',
        html: '原本最初的作法是 : 修改數據就更新到firestore數據庫上，結果某一次測試輸入太多文字，firestore就爆流量限制問題了...',
      },
      className: 'style-text-color__default',
    },
    {
      type: 'quote',
      id: 'iu8m7k4ca2ao75b',
      parentId: '',
      content: {
        text: '免費的不要要求太多...',
        html: '免費的不要要求太多...',
      },
      className: 'style-text-color__default',
    },
    {
      type: 'p',
      id: 'lvrl4irw23oiri',
      parentId: '',
      content: {
        text: '所以目前資料的保存，會在每一次的編輯立馬更新到localstorage上，這是目前的暫緩作法。(不用特地到localstorage改資料，已經做加密處理，除非你要清空所有資料...)',
        html: '所以目前資料的保存，會在每一次的編輯立馬更新到localstorage上，這是目前的暫緩作法。(不用特地到localstorage改資料，已經做加密處理，除非你要清空所有資料...)',
      },
      className: 'style-text-color__default',
    },
    {
      type: 'p',
      id: 'vt5ca2owpqbepe',
      parentId: '',
      content: {
        text: ' ',
        html: '<br>',
      },
      className: 'style-text-color__default',
    },
    {
      type: 'p',
      id: 'a0g37lp49iebohl',
      parentId: '',
      content: {
        text: '因此目前使用者在此網站上輸入任何內容都會是保存狀態。',
        html: '因此目前使用者在此網站上輸入任何內容都會是保存狀態。',
      },
      className: 'style-text-color__default',
    },
    {
      type: 'p',
      id: 'pie9npuhsccna9',
      parentId: '',
      content: {
        text: '若想要在其他台電腦使用當前資料繼續編輯，請按下畫面最右上方的 -更新到數據庫- ，會直接把資料儲存到雲端數據庫中',
        html: '若想要在其他台電腦使用當前資料繼續編輯，請按下畫面最右上方的 -更新到數據庫- ，會直接把資料儲存到雲端數據庫中',
      },
      className: 'style-text-color__default',
    },
    {
      type: 'p',
      id: 'xirwbktp98rw9p',
      parentId: '',
      content: {
        text: '',
        html: '',
      },
      className: 'style-text-color__default',
    },
    {
      type: 'h2',
      id: '7vi9tcnt0ovs3hx',
      parentId: '',
      content: {
        text: '一直點左邊的按鈕增加block(區塊)好麻煩，有沒有快捷鍵?',
        html: '一直點左邊的按鈕增加block(區塊)好麻煩，有沒有快捷鍵?',
      },
      className: 'style-text-color__default',
    },
    {
      type: 'todoItem',
      id: '8b4l84jxl6jv4jv',
      parentId: '',
      content: {
        text: '有',
        html: '有',
        isChecked: true,
      },
      className: 'style-text-color__default',
    },
    {
      type: 'todoItem',
      id: 'ff77g71bybvpur',
      parentId: '',
      content: {
        text: '作者太懶了，沒有',
        html: '作者太懶了，沒有',
        isChecked: false,
      },
      className: 'style-text-color__default',
    },
    {
      type: 'p',
      id: 'q58gjuch6fdw8er',
      parentId: '',
      content: {
        text: '',
        html: '',
      },
      className: 'style-text-color__default',
    },
    {
      type: 'p',
      id: 'gnqa4830deu4bwq',
      parentId: '',
      content: {
        text: '可以輸入以下快捷鍵，並按下Enter，即可轉換為其他類型的block',
        html: '可以輸入以下快捷鍵，並按下Enter，即可轉換為其他類型的block',
      },
      className: 'style-text-color__default',
    },
    {
      type: 'bulletItem',
      id: '4jyvq3zqohr65d5',
      parentId: '',
      content: {
        text: '/h1',
        html: '/h1',
        indent: 0,
      },
      className: 'style-text-color__default',
    },
    {
      type: 'bulletItem',
      id: 'pqwq48p6d69hl',
      parentId: '',
      content: {
        text: '/h2',
        html: '/h2',
        indent: 0,
      },
      className: 'style-text-color__default',
    },
    {
      type: 'bulletItem',
      id: 'pi756lq8l69pt',
      parentId: '',
      content: {
        text: '/h3',
        html: '/h3',
        indent: 0,
      },
      className: 'style-text-color__default',
    },
    {
      type: 'bulletItem',
      id: 'gjuzhaevak69uy',
      parentId: '',
      content: {
        text: '/vid',
        html: '/vid',
        indent: 0,
      },
      className: 'style-text-color__default',
    },
    {
      type: 'bulletItem',
      id: 'gpzw3je85x46a02',
      parentId: '',
      content: {
        text: '/img',
        html: '/img',
        indent: 0,
      },
      className: 'style-text-color__default',
    },
    {
      type: 'bulletItem',
      id: 'sfb0jwfxhtc6a4y',
      parentId: '',
      content: {
        text: '/p',
        html: '/p',
        indent: 0,
      },
      className: 'style-text-color__default',
    },
    {
      type: 'bulletItem',
      id: '4p6s13i710c6aa2',
      parentId: '',
      content: {
        text: '/pag',
        html: '/pag',
        indent: 0,
      },
      className: 'style-text-color__default',
    },
    {
      type: 'bulletItem',
      id: '5qv6c1s026c6afe',
      parentId: '',
      content: {
        text: '/num',
        html: '/num',
        indent: 0,
      },
      className: 'style-text-color__default',
    },
    {
      type: 'bulletItem',
      id: 'hvycs1fo0nf6aky',
      parentId: '',
      content: {
        text: '/bul',
        html: '/bul',
        indent: 0,
      },
      className: 'style-text-color__default',
    },
    {
      type: 'bulletItem',
      id: 'zkpv72dinwc6aqa',
      parentId: '',
      content: {
        text: '/todo',
        html: '/todo',
        indent: 0,
      },
      className: 'style-text-color__default',
    },
    {
      type: 'bulletItem',
      id: 'xiuck8vc7tc6avu',
      parentId: '',
      content: {
        text: '/div',
        html: '/div',
        indent: 0,
      },
      className: 'style-text-color__default',
    },
    {
      type: 'bulletItem',
      id: 'rax7q8qawqf6b1e',
      parentId: '',
      content: {
        text: '/code',
        html: '/code',
        indent: 0,
      },
      className: 'style-text-color__default',
    },
    {
      type: 'bulletItem',
      id: 'upba9dfscmi6b6q',
      parentId: '',
      content: {
        text: '/quo',
        html: '/quo',
        indent: 0,
      },
      className: 'style-text-color__default',
    },
    {
      type: 'bulletItem',
      id: 'dwyxkti2af6bde',
      parentId: '',
      content: {
        text: '/link',
        html: '/link',
        indent: 0,
      },
      className: 'style-text-color__default',
    },
  ],
};

export default firstPageData;
